---
- name: Check journal_forwarder role variables
  debug:
    msg:
      - "journal_forwarder role loaded successfully"
      - "journal_forwarder_install: {{ journal_forwarder_install }}"
      - "graylog_gelf_host: {{ graylog_gelf_host }}"
      - "graylog_gelf_port: {{ graylog_gelf_port }}"
      - "graylog_gelf_mode: {{ graylog_gelf_mode }}"

...
