---
- name: Install repository packages for journal_forwarder
  ansible.builtin.package:
    name: "{{ pkg_rhel_journal_forwarder_repositories }}"
    state: present
  when:
    - journal_forwarder_install | bool
    - ansible_os_family == 'RedHat'

- name: Validate mandatory variables
  ansible.builtin.assert:
    that:
      - graylog_gelf_host is defined
      - graylog_gelf_host | length > 0
      - graylog_gelf_port is defined
      - graylog_gelf_mode in ['tcp', 'udp']
    fail_msg: "Mandatory variables graylog_gelf_host, graylog_gelf_port and graylog_gelf_mode must be valid"
  when: journal_forwarder_install | bool

...
