---
- name: Install Fluent Bit on Ubuntu
  ansible.builtin.apt:
    name: "{{ pkg_debian_fluent_bit }}"
    state: present
  notify: restart fluent-bit
  when: journal_forwarder_install | bool

- name: Install audit packages on Ubuntu
  ansible.builtin.apt:
    name: "{{ pkg_debian_journal_forwarder_audit }}"
    state: present
  when:
    - journal_forwarder_install | bool
    - journal_forwarder_audit_enabled | bool

...
